## Numpy Library

### Used to create multidimensional arrays and many array operations

In [1]:
import numpy as np 
print(np.__version__)

1.20.3


## Arrays - Data structure that stores same data type

In [1]:
import numpy as np

In [2]:
# 1-D array

lst = [1,2,3,4]
arr=np.array(lst)
print(arr)
print(arr.ndim)  # will check the dimensions of array

[1 2 3 4]
1


In [3]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(3, 5)

In [6]:
# 2-D array

lst1=[1,3,5,7,9]
lst2=[2,4,6,8,10]
lst3=[11,12,13,14,15]
arr=np.array([lst1,lst2,lst3])
print(arr)
type(arr)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [11 12 13 14 15]]


numpy.ndarray

In [8]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9,  2],
       [ 4,  6,  8],
       [10, 11, 12],
       [13, 14, 15]])

### indexing

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[4]

5

In [4]:
lst1=[1,3,5,7,9]
lst2=[2,4,6,8,10]
lst3=[11,12,13,14,15]
arr=np.array([lst1,lst2,lst3])
print(arr)
print("This is",arr.ndim,"-dimensional array")
arr[1:,0:2]
arr[0:2,2:4]


[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [11 12 13 14 15]]
This is 2 -dimensional array


array([[5, 7],
       [6, 8]])

In [3]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr)
arr[1,:1]
arr[1,0]

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


50

In [30]:
arr=np.arange(1,11,step=2)
print(arr)

[1 3 5 7 9]


In [31]:
arr=np.linspace(1,10,50)
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [33]:
# copy function and broadcasting

arr=np.array([1,2,3,4,5,6,7,8,9])
arr[4:]=10
arr

array([ 1,  2,  3,  4, 10, 10, 10, 10, 10])

In [44]:
arr1=arr
arr1[4:]=500
print("Changed list= ",arr1)

Changed lis=  [  1   2   3   4 500 500 500 500 500]


In [43]:
print("Here it will change the values in list permanently as it takes the same memory space")
print("Original array list=",arr)

Here it will change the values in list permanently as it takes the same memory space
Original array list= [  1   2   3   4 500 500 500 500 500]


In [41]:
arr1=arr.copy()
print("arr= ",arr)
arr1[4:]=600
print("arr1= ",arr1)
print("copy function creates new memory space for the chaange hence the original array list will stay as it it")
print("Original list= ",arr)

arr=  [  1   2   3   4 500 500 500 500 500]
arr1=  [  1   2   3   4 600 600 600 600 600]
copy function creates new memory space for the chaange hence the original array list will stay as it it
Original list=  [  1   2   3   4 500 500 500 500 500]


In [45]:
arr

array([  1,   2,   3,   4, 500, 500, 500, 500, 500])

In [46]:
arr*2

array([   2,    4,    6,    8, 1000, 1000, 1000, 1000, 1000])

In [50]:
arr>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [54]:
arr[arr<400]

array([1, 2, 3, 4])

In [55]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
arr1*arr2

array([ 4, 10, 18, 28])

In [58]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.array([[1,3,5],
               [2,4,6],
               [1,2,3]])
arr1*arr2

array([[ 1,  6, 15],
       [ 8, 20, 36],
       [ 7, 16, 27]])

In [60]:
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.array([[1,3],
               [2,4],
               [1,2]])
arr1*arr2

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [65]:
arr=np.ones(4)  # bydef dtype is float
print(arr)
arr1=np.ones(5,dtype=int)
print(arr1)

[1. 1. 1. 1.]
[1 1 1 1 1]


In [67]:
np.ones([3,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
np.random.rand(4,4)  # all elements are between 0 to 1 and everytime we execute the values will change randomly

array([[0.53302934, 0.97960691, 0.56794408, 0.96430882],
       [0.9534034 , 0.61985734, 0.49721216, 0.27790461],
       [0.00782947, 0.89873855, 0.68526919, 0.43575899],
       [0.398345  , 0.46386479, 0.91782015, 0.88346631]])

In [72]:
np.random.randn(3,3)  #standard normal distribution

array([[0.77934338, 1.05365438, 0.54989476],
       [0.71199621, 0.75706168, 1.55239113],
       [0.53856875, 0.24489474, 0.61958662]])

In [73]:
np.random.randint(0,100,8)

array([79, 41, 84,  0, 41, 28, 40, 90])

In [75]:
np.random.randint(0,100,8).reshape(2,4)

array([[84,  3,  7, 52],
       [42, 85, 61, 66]])

In [77]:
np.random.random_sample((1,6)).reshape(2,3)

array([[0.08871622, 0.06544875, 0.28054533],
       [0.12709976, 0.16546563, 0.19858306]])

In [18]:
# 3-D array

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr)
print(arr.ndim)

arr[0,1,2]
arr[1,0,-2]

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3


8

In [9]:
# higher dimensional array

arr=np.array([1,2,3,4], ndmin=6)     # ndmin = tells how many dimensions w ewant
print(arr)
arr.ndim

[[[[[[1 2 3 4]]]]]]


6

### Slicing  (start_index : end_index : step)

In [22]:
# Slicing 1-D array

arr=[1,2,3,4,5,6,7,8]
print(arr[4:])
print(arr[-4:-1])
print(arr[1:6:3])

[5, 6, 7, 8]
[5, 6, 7]
[2, 5]


In [28]:
# Slicing 2-D array

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0,1:4])
print(arr[1,-4:-1])
print(arr[0:2,3])    # 0:2 means 0th and 1st row AND 3 means 3rd col index)

[2 3 4]
[7 8 9]
[4 9]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)   # to find data type of array elements or list

int32


In [5]:
arr=np.array(['apple','banana','mango'])
print(arr.dtype)

<U6


In [6]:
arr=np.array([1,1,1,1],dtype='S')
print(arr.dtype)

|S1


In [8]:
arr=np.array([1,1,1,1],dtype='i8')
print(arr.dtype)

int64


In [9]:
arr=np.array([1,1,1,1],dtype='i4')
print(arr.dtype)

int32


In [13]:
arr = np.array(['a', '2', '3'], dtype='i')
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [15]:
arr=np.array([1.3,1.4,4.5])
print(arr.dtype)
arr1=arr.astype('int')
print(arr1)
print(arr1.dtype)

float64
[1 1 4]
int32


## Iteration

In [5]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in arr:
    print(i)
    
    
for j in np.nditer(arr):
    print(j)
    
# OR

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [8]:
# Itearting with differnt data types
''' we use op_dtypes argument and pass it the data type which we expect and flags=['buffered'] is used because numpy doesn't 
change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action
'''

arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):       # Here int is converted to string
    print(x)

    

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


In [17]:
# iteration using different step size

arr=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr[:,1::2]):
    print(i)

2
5


In [21]:
# Enumerated Iteration using ndenumerate()
# Enumeration means mentioning sequence number of somethings one by one. It'll print elements with index number

arr=np.array([[1,2,3],[4,5,6]])
for idx, x in np.ndenumerate(arr):
    print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## Joining arrays

In [23]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [31]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate((arr1,arr2))     # In 2-D arrays by default axis is 0 
print(arr)
print("\n")

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Spliting arrays

In [33]:
arr=np.array([1,2,3,4,5,6])
arr1=np.array_split(arr,3)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [38]:
arr=np.array([1,2,3,4,5,6])
arr1=np.array_split(arr,4)
print(arr1)

print(arr1[0])
print(arr1[2])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[5]


In [37]:
arr=np.array([1,2,3,4,5,6])
arr1=np.array_split(arr,7)
print(arr1)

print("\n")

print(arr1[0])
print(arr1[2])

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


[1]
[3]


In [41]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr1=np.array_split(arr,3)
print(arr1)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]])]


In [42]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr1=np.array_split(arr,3,axis=1)
print(arr1)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15]])]


In [44]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arr1=np.hsplit(arr,3)
print(arr1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15]])]


## Searching

In [47]:
arr=np.array([1,2,3,4,5,6,5])
print(np.where(arr==5))
print(np.where (arr%2==0))

(array([4, 6], dtype=int64),)
(array([1, 3, 5], dtype=int64),)


In [52]:
# Searchsorted

arr=np.array([1,2,3,4,5,6,5])
print(np.searchsorted(arr,5))
print(np.searchsorted(arr,5,side='right'))

4
5


In [54]:
arr=np.array([1,2,3,4,5,6,5])  
print(np.searchsorted(arr,[22,12,4]))        # will tell you at what index can we insert these values

[7 7 3]


## Filtering

In [56]:
arr=np.array([11,22,33,44])
x=[True,False,True,True]
arr1=arr[x]
print(arr1)     # will return only values which are true

[11 33 44]


In [63]:
arr=np.array([11,22,33,44])
new_arr=[]
for x in arr:
    if x>20:
        new_arr.append(True)
    else:
        new_arr.append(False)
print(new_arr)
y=arr[new_arr]
print(y)

#OR

arr=np.array([11,22,33,44])
new_arr=arr>20
print(new_arr)
y=arr[new_arr]
print(y)


[False, True, True, True]
[22 33 44]
[False  True  True  True]
[22 33 44]


In [66]:
arr=np.array([3,6,5,8,9,66,6,44])
arr1=[]
for x in arr:
    if x%2==0:
        arr1.append(True)
    else:
        arr1.append(False)
print(arr1)
newarr=arr[arr1]
print(newarr)

#OR

arr=np.array([3,6,5,8,9,66,6,44])
arr1=arr%2==0
print(arr1)
newarr=arr[arr1]
print(newarr)

[False, True, False, True, False, True, True, True]
[ 6  8 66  6 44]
[False  True False  True False  True  True  True]
[ 6  8 66  6 44]


# Sorting

In [67]:
arr=np.array([1,9,6,8,0])
print(np.sort(arr))

[0 1 6 8 9]


In [70]:
arr=np.array(['banana','barry','cherry','apple','Barry','grapes'])
print(np.sort(arr))

['Barry' 'apple' 'banana' 'barry' 'cherry' 'grapes']


In [73]:
arr=np.array([True,False,True,True,False])
print(np.sort(arr))

[False False  True  True  True]


In [74]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
